---
name: build-arch-package
description: Build an Arch Linux package
inputs:
  DIR:
    description: PKGBUILD directory
    required: true
branding:
  color: blue
  icon: archive
runs:
  using: node12
  main: index.js
