---
name: build-arch-package
description: Build an Arch Linux package
inputs:
  DIR:
    description: PKGBUILD directory
    required: true
branding:
  color: blue
  icon: archive
runs:
  using: composite
  steps:
    - run: /__w/_actions/duament/build-arch-package/master/run.sh
      shell: bash
      env:
        INPUT_DIR: ${{ inputs.DIR }}
