---
name: build-arch-package
description: Build an Arch Linux package
inputs:
  PKGBUILD:
    description: PKGBUILD directory
    required: true
  OUTDIR:
    description: Output directory to store the built package (relative to $HOME)
    required: false
    default: $HOME/arch-packages
  PARAM:
    description: Optional param for extra-x86_64-build
    required: false
    default: ''
branding:
  color: blue
  icon: archive
runs:
  using: node12
  main: index.js
